### ISSUE TITLE
Smoke tests for pre-provisioned service do not cover TLS

### ISSUE THREAD

**Issue by coro** [pivotal-cf/cf-rabbitmq-smoke-tests-release#55]
[Currently](https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release/blob/d04d52522e23174994eb223519748cbabec9430f/src/rabbitmq-smoke-tests/tests/smoke_tests.go#L27-L34), the smoke tests only create services with TLS enabled if the service offering is `p.rabbitmq`, i.e. the on-demand service. This means the [tls_support](https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release/blob/master/jobs/smoke-tests/spec#L51-L53) property in the pre-provisioned smoke test job is meaningless and does not affect the running of the test.

The smoke tests should support creating TLS-enabled pre-provisioned SIs as part of running the tests.

**Comment by MirahImage** [comment]
After testing this, the smoke tests do test TLS support for pre-provisioned SIs as part of running the tests, independent of the `tls_support` property. Instead, this behaviour is determined by whether certificates are configured in the multi-tennant `p-rabbitmq` instance. If certificates are configured, then the service key will contain the `amqp+ssl` and `amqps` protocols, which will be tested by the smoke test, and will result in a smoke test failure if the certificates are invalid.

The resolution to the issue is then to make it clear the `tls_support` property applies only to on-demand `p.rabbitmq` instances.
